spring.datasource.url=jdbc:postgresql://localhost:5432/forgewatch
spring.datasource.username=forgewatch
spring.datasource.password=forgewatch

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=truespring.application.name=forgewatch-backend
spring.jpa.open-in-view=false